# Run_specific parameters

dataset_type: "online_pricing"
dataset_number: 1

normalize_features: False
lag_window_params: null
# Other parameters:
unit_size: 0.01

# General parameters for experimental set-up
nb_features: 1
covariance: 0.2
noise_std: 0.5
function_form: "linear"
size_train: 1000
size_test: 0
size_val: 0

env_kwargs:
    alpha: [10]
    beta: [-1]
    p_bound_low: 0
    p_bound_high: 10

    gamma: 0.0 # added for learning stability, not relevant for our problem as such
    horizon_train: 1000

