# for grouping of training run
agent: "RL2PPO" #lERMMeta

n_epochs: 40000
n_steps: null 

val_every: 250
number_eval: 16
early_stopping_patience: 30
early_stopping_warmup: 10 #30
save_best: True
results_dir: "results"