# Run_specific parameters

### Agent functions:

SAC:
  learning_rate_actor: 0.0001
  learning_rate_critic: 0.005
  initial_replay_size: 8192
  max_replay_size: 750000
  batch_size: 64
  hidden_layers: [256, 256]
  activation: "relu"
  warmup_transitions: 1000
  lr_alpha: 0.003
  tau: 0.0015
  log_std_min: -20
  log_std_max: 2
  target_entropy: -3
  use_log_alpha_loss: True
  optimizer: "Adam"
  loss: "MSE"
  device: "cpu"

Greedy:
  ex_prices: [[0.5], [5]]
  link: linear

