# Run_specific parameters

### Agent functions:

SAC:
  learning_rate_actor: 0.001
  learning_rate_critic: 0.004
  initial_replay_size: 64
  max_replay_size: 1024
  batch_size: 32
  hidden_layers: [64, 32]
  activation: "relu"
  warmup_transitions: 16
  lr_alpha: 0.00005
  tau: 0.0002
  log_std_min: -20
  log_std_max: 2
  target_entropy: -2.5
  use_log_alpha_loss: True
  optimizer: "Adam"
  loss: "MSE"
  device: "cpu"

Greedy:
  ex_prices: [[4], [6]]
  link: linear

ILQX:
  ex_prices: [[4], [6]]
  link: linear
