# for grouping of training run
agent: "Clairvoyant" #lERMMeta

n_epochs: 100
n_steps: null 

val_every: 5
number_eval: 16
early_stopping_patience: 10
early_stopping_warmup: 5 #30
save_best: True
results_dir: "results"